---
- hosts: webservers

  pre_tasks:
  - name: Ensure the latest version of nginx is installed
    package: name=nginx state=latest
    become: yes

  roles:
   - deploy-site
  become: yes

  post_tasks:
  - name: Make sure the site is working
    local_action: command npm test
    args:
      chdir: /Users/orjan/Code/ica/smoketest
    delegate_to: smokerunner
    become: no
